title: KAIST Urban AI
description: KAIST Urban AI (KUAI)
baseurl: "/kaist-uaii.github.io"                 # 프로젝트 사이트면 "/<repo-name>"
url: "https://kaist-uaii.github.io"
markdown: kramdown
plugins: []
